# Generated by Django 3.2.7 on 2022-05-17 09:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_auto_20220517_0920'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='dislikes',
        ),
        migrations.RemoveField(
            model_name='like',
            name='liker',
        ),
        migrations.RemoveField(
            model_name='like',
            name='likes',
        ),
        migrations.AddField(
            model_name='like',
            name='haters',
            field=models.ManyToManyField(related_name='haters', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='like',
            name='likers',
            field=models.ManyToManyField(related_name='likers', to=settings.AUTH_USER_MODEL),
        ),
    ]
