# Generated by Django 3.2.7 on 2022-05-17 10:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_auto_20220517_0942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='likers',
            field=models.ManyToManyField(blank=True, default='', null=True, related_name='likers', to=settings.AUTH_USER_MODEL),
        ),
    ]
