# Generated by Django 3.2.7 on 2022-05-24 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0005_auto_20220517_1450'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newpost',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AlterField(
            model_name='newpost',
            name='content',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
