# Generated by Django 3.2.7 on 2022-06-20 12:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0016_auto_20220614_1126'),
    ]

    operations = [
        migrations.AddField(
            model_name='newpost',
            name='haters',
            field=models.ManyToManyField(blank=True, null=True, related_name='haters', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='newpost',
            name='likers',
            field=models.ManyToManyField(blank=True, null=True, related_name='likers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Like',
        ),
    ]
